# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TechMarket' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    pod 'RxSwift', '6.5.0'
    pod 'RxCocoa', '6.5.0'
    pod 'RxDataSources', '~> 5.0'
    pod 'Then'
    pod 'SnapKit'

  # Pods for TechMarket

  target 'TechMarketTests' do
    inherit! :search_paths
    pod 'RxBlocking', '6.5.0'
    pod 'RxTest', '6.5.0'  end

  target 'TechMarketUITests' do
    # Pods for testing
  end

end
